language: node_js
addons:
  firefox: "latest"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - gem install scss-lint
  - npm install -g npm@2
  - npm install
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
script:
  # - npm run lint
  - npm run test:karma
